[config]
rpc = "https://api.testnet.iota.cafe"

[packages]
AMM = { local = "../../../move/amm" }
Examples = { local = "../../../move/examples" }
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "develop" }

