[config]
# IOTA mainnet RPC endpoint
rpc = "https://fullnode.mainnet.sui.io:443"

[packages]
# Your on-chain package - replace "MyPackage" with a descriptive name
MyPackage = { id = "0xcfe7f4b11829a0e31987f9a1c10186114419ee92a02dd22054894b45139b0704" }

# Optional: Add IOTA framework if you need to reference IOTA types
# Iota = { id = "0x2" }

# Optional: Add Move stdlib if needed
# MoveStdlib = { id = "0x1" }

# You can also add source packages from git or local paths:
# LocalPackage = { local = "../path/to/move/package" }
# GitPackage = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "develop" }
